### ISSUE TITLE
Allow GET for some endpoints

### ISSUE THREAD

**Issue by augi** [avast/grpc-json-bridge#3]
It would be nice to allow also HTTP GET for some endpoints, e.g. for all methods starting with `Get`. Or better - make it configurable.

We would have to solve how to translate query parameters to JSON body but it could be easy as `?par=value` -> `"par": "value"` - just numbers and arrays should be handled in a special way.

[This definition of protobuf-JSON mapping](https://developers.google.com/protocol-buffers/docs/proto3#json) could help.

**Comment by petr-k** [comment]
Theoretically, we could draw some inspiration or directly use what Google already does in their API's - https://github.com/googleapis/googleapis/blob/master/google/api/http.proto. It's also being used in the https://github.com/grpc-ecosystem/grpc-gateway project.

But anyway, what exactly is the motivation here? The only one I can think if is in-browser caching of `GET` requests, which would also require handling of caching-related HTTP headers for it to make any sense.

**Comment by augi** [comment]
The motivation was that users could `curl` an URL and that URL would contain all the parameters. So they wouldn't have to specify the JSON payload and the URL.

This is definitely just nice-to-have feature.

Btw. are you aware of any HTTP server that reads the Google API annotations?

**Comment by jendakol** [comment]
I see it in very similar way as Petr. IMHO when user uses `curl`, it's not a problem to use JSON format (and it will be even more error-proof).

**Comment by augi** [comment]
```sh
curl https://myservice/com.avast.myservice.EndPoint/GetProgress/1
```
vs.
```
curl -H "Content-Type: application/json" -X POST -d '{"id":"1"}' https://myservice/com.avast.myservice.EndPoint/GetProgress/1
```
As I said, it would be just nice to have.

If we wanted to make it more configurable then we could support the Google API annotations, but it would be out of scope of this project.

The aim of this project is to provide seamless JSON<->gRPC bridge without any additional configuration. So closing this ticket...
