### ISSUE TITLE
Status endpoint

### ISSUE THREAD

**Issue by augi** [avast/grpc-json-bridge#4]
It would be nice to provide a status endpoint that could be used for health-checking.

Plain HTTP 200 response would be sufficient for now, it could be customized later.

It's related to modules that will provide the HTTP connectivity (spray? play? http4s? check [this comparison](https://scala.libhunt.com/categories/663-http)).

**Comment by petr-k** [comment]
I believe that's out of scope of this library. I think it is the responsibility of the host application to include a healthcheck as desired.

**Comment by augi** [comment]
IMHO it depends how the HTTP connectivity module will be implemented.

If it delivered an instance of a HTTP server then I believe it could be useful to provide also `/status` endpoint. Many services are so simple, and it would overkill to include another HTTP server to the project, just to provide status endpoint.

If the HTTP-connectivity module provided just a fraction of a HTTP server configuration, then it's really up to the application.

**Comment by augi** [comment]
The endpoint that lists all available services (#17) is sufficient - it can be used easily as a status endpoint.
