### ISSUE TITLE
Fails to load classes for namespaced services

### ISSUE THREAD

**Issue by sideeffffect** [avast/grpc-json-bridge#45]
```
Classes cannot be loaded: com.avast.viruslab.scavenger.detections.general.com/avast/viruslab/scavenger/detections/general/proto.GeneralServiceGrpc$, com.avast.viruslab.scavenger.detections.general.GeneralServiceGrpc$
```

```
syntax = "proto3";

package com.avast.viruslab.scavenger.detections.general;

service GeneralService {
...
```

**Comment by augi** [comment]
Could you please provide us with an example project that fails? Or it would be also sufficient to alter the existing tests to make them fail.
Thanks!

**Comment by jendakol** [comment]
@sideeffffect You have to specify `option java_package` too. Without that, it's impossible to find the class - this is caused by the current implementation (based on reflection).
